version: '3.0'
services:
  minio:
    image: 'minio/minio:RELEASE.2023-07-21T21-12-44Z'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server --console-address ":9001" /data

  spark:
    container_name: local-spark
    build:
      context: ./
      dockerfile: containers/spark/Dockerfile
    ports:
      - '4040:4040'
    volumes:
      - ./equipment:/opt/spark/work-dir/equipment